-- GENERATED from categories.json by scripts/generate-categories-sql.ts — edit categories.json, then regenerate.
-- Safe to re-run: existing categories are updated in place.
insert into categories (key, label, group_label, reconfirmation_rule, property_label, item_label, property_fields, item_fields, price_unit_options)
values
  ('league_tournament', 'League and tournament', 'Rights and sponsorship', 'sponsorship', 'League season', 'Tier or asset (title, LED, pitch mat)', $json$[{"key":"league_name","type":"text","required":true},{"key":"sport","type":"text","required":true},{"key":"season_year","type":"text","required":true},{"key":"market","type":"text","required":true},{"key":"event_dates","type":"date_range","required":false},{"key":"broadcast_reach","type":"text","required":false},{"key":"gaming_brand_acceptance","type":"select","options":["accepted","case_by_case","not_accepted"],"required":true},{"key":"exclusivity","type":"text","required":false}]$json$::jsonb, $json$[{"key":"asset_type","type":"select","options":["title_sponsorship","led_perimeter","pitch_mat","kit_asset","other"],"required":true},{"key":"unit_description","type":"text","required":false},{"key":"quantity","type":"number","required":false}]$json$::jsonb, $json$["flat","per_match","per_season"]$json$::jsonb),
  ('team', 'Team', 'Rights and sponsorship', 'sponsorship', 'Team season', 'Kit or asset position', $json$[{"key":"team_name","type":"text","required":true},{"key":"sport","type":"text","required":true},{"key":"season_year","type":"text","required":true},{"key":"market","type":"text","required":true},{"key":"event_dates","type":"date_range","required":false},{"key":"gaming_brand_acceptance","type":"select","options":["accepted","case_by_case","not_accepted"],"required":true}]$json$::jsonb, $json$[{"key":"asset_position","type":"select","options":["shirt_front","shirt_back","sleeve","shorts","led","other"],"required":true}]$json$::jsonb, $json$["flat","per_season"]$json$::jsonb),
  ('player_athlete', 'Player and athlete', 'Rights and sponsorship', '90day', 'Player', 'Rights package', $json$[{"key":"player_name","type":"text","required":true},{"key":"sport","type":"text","required":true},{"key":"markets","type":"text","required":true},{"key":"management_contact","type":"text","required":false},{"key":"gaming_brand_acceptance","type":"select","options":["accepted","case_by_case","not_accepted"],"required":true}]$json$::jsonb, $json$[{"key":"package_type","type":"select","options":["ambassador","appearance","social_content","other"],"required":true},{"key":"term_length","type":"text","required":false}]$json$::jsonb, $json$["per_year","per_appearance","flat"]$json$::jsonb),
  ('celebrity_talent', 'Celebrity and talent', 'Rights and sponsorship', '90day', 'Talent', 'Endorsement package', $json$[{"key":"talent_name","type":"text","required":true},{"key":"category","type":"text","required":false},{"key":"markets","type":"text","required":true},{"key":"management_contact","type":"text","required":false},{"key":"gaming_brand_acceptance","type":"select","options":["accepted","case_by_case","not_accepted"],"required":true}]$json$::jsonb, $json$[{"key":"package_type","type":"select","options":["endorsement","appearance","content","other"],"required":true}]$json$::jsonb, $json$["per_year","per_appearance","flat"]$json$::jsonb),
  ('influencer_creator', 'Influencer and creator', 'Creators', '60day', 'Creator', 'Deliverable', $json$[{"key":"creator_name","type":"text","required":true},{"key":"platform","type":"select","options":["instagram","tiktok","youtube","twitch","x","other"],"required":true},{"key":"follower_count","type":"number","required":false},{"key":"markets","type":"text","required":true},{"key":"gaming_brand_acceptance","type":"select","options":["accepted","case_by_case","not_accepted"],"required":true},{"key":"roster_exclusivity","type":"boolean","required":false}]$json$::jsonb, $json$[{"key":"deliverable_type","type":"select","options":["post","reel","story","video","livestream","bundle"],"required":true},{"key":"quantity","type":"number","required":false}]$json$::jsonb, $json$["per_deliverable","per_campaign","flat"]$json$::jsonb),
  ('broadcast_streaming', 'Broadcast and streaming', 'Media', 'sponsorship', 'Channel or platform', 'Ad product', $json$[{"key":"channel_name","type":"text","required":true},{"key":"markets","type":"text","required":true},{"key":"event_dates","type":"date_range","required":false},{"key":"gaming_brand_acceptance","type":"select","options":["accepted","case_by_case","not_accepted"],"required":true}]$json$::jsonb, $json$[{"key":"ad_product","type":"select","options":["spot","sponsorship_billboard","overlay","integration","other"],"required":true}]$json$::jsonb, $json$["flat","per_spot","per_match"]$json$::jsonb),
  ('digital_publisher_app', 'Digital publisher and app', 'Media', '60day', 'Site or app', 'Ad product', $json$[{"key":"site_or_app_name","type":"text","required":true},{"key":"markets","type":"text","required":true},{"key":"monthly_traffic","type":"text","required":false},{"key":"gaming_brand_acceptance","type":"select","options":["accepted","case_by_case","not_accepted"],"required":true}]$json$::jsonb, $json$[{"key":"ad_product","type":"select","options":["banner","takeover","native","push","other"],"required":true}]$json$::jsonb, $json$["per_week","per_month","cpm","flat"]$json$::jsonb),
  ('ooh_led', 'OOH and LED', 'Media', '60day', 'Site or network', 'Slot for a period', $json$[{"key":"site_or_network_name","type":"text","required":true},{"key":"markets","type":"text","required":true},{"key":"gaming_brand_acceptance","type":"select","options":["accepted","case_by_case","not_accepted"],"required":true}]$json$::jsonb, $json$[{"key":"slot_period","type":"text","required":false},{"key":"location_detail","type":"text","required":false}]$json$::jsonb, $json$["per_match","per_week","flat"]$json$::jsonb),
  ('transit_vehicle', 'Transit and vehicle', 'Media', '60day', 'Fleet', 'Branding package', $json$[{"key":"fleet_operator","type":"text","required":true},{"key":"markets","type":"text","required":true},{"key":"gaming_brand_acceptance","type":"select","options":["accepted","case_by_case","not_accepted"],"required":true}]$json$::jsonb, $json$[{"key":"vehicle_count","type":"number","required":false},{"key":"branding_type","type":"select","options":["full_wrap","partial_wrap","interior","other"],"required":true}]$json$::jsonb, $json$["flat","per_vehicle"]$json$::jsonb),
  ('ip_shows', 'IP and shows', 'IP and content', 'sponsorship', 'Show or IP', 'Integration', $json$[{"key":"show_or_ip_name","type":"text","required":true},{"key":"markets","type":"text","required":true},{"key":"event_dates","type":"date_range","required":false},{"key":"gaming_brand_acceptance","type":"select","options":["accepted","case_by_case","not_accepted"],"required":true}]$json$::jsonb, $json$[{"key":"integration_type","type":"select","options":["product_placement","branded_segment","co_created","other"],"required":true}]$json$::jsonb, $json$["flat","per_episode"]$json$::jsonb),
  ('content_production', 'Content and production', 'IP and content', '90day', 'Production vendor', 'Package', $json$[{"key":"vendor_name","type":"text","required":true},{"key":"markets","type":"text","required":true},{"key":"gaming_brand_acceptance","type":"select","options":["accepted","case_by_case","not_accepted"],"required":true}]$json$::jsonb, $json$[{"key":"package_type","type":"select","options":["shoot_day","edit_package","full_campaign","other"],"required":true}]$json$::jsonb, $json$["flat","per_day"]$json$::jsonb),
  ('events_activations', 'Events and activations', 'On-ground', 'sponsorship', 'Event', 'Partnership package', $json$[{"key":"event_name","type":"text","required":true},{"key":"markets","type":"text","required":true},{"key":"event_dates","type":"date_range","required":true},{"key":"gaming_brand_acceptance","type":"select","options":["accepted","case_by_case","not_accepted"],"required":true}]$json$::jsonb, $json$[{"key":"package_type","type":"select","options":["title_partner","activation_booth","sampling","other"],"required":true}]$json$::jsonb, $json$["flat","per_day"]$json$::jsonb)
on conflict (key) do update set
  label = excluded.label, group_label = excluded.group_label, reconfirmation_rule = excluded.reconfirmation_rule,
  property_label = excluded.property_label, item_label = excluded.item_label,
  property_fields = excluded.property_fields, item_fields = excluded.item_fields, price_unit_options = excluded.price_unit_options;
